### ISSUE TITLE
Conda broke after the newly released Big Sur 11.2.2 (Apple M1) update.

### ISSUE THREAD

**Issue by daiyoba** [conda-forge/miniforge#130]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

conda or python was killed immediately.

<br/>
Environment (<code>conda list</code>):
<details>
Process:               python3.9 [10799]
Path:                  /opt/homebrew/*/python3.9
Identifier:            python3.9
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [2803]
Responsible:           Terminal [2801]
User ID:               501

Date/Time:             2021-02-28 14:21:01.395 +0800
OS Version:            macOS 11.2.2 (20D80)
Report Version:        12
Anonymous UUID:        797CB66F-2447-13D7-A6C3-66964211EF2C

Time Awake Since Boot: 4800 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000100edc000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000100edc000   x1: 0x000000016ef23828   x2: 0x000000016ef237d8   x3: 0x00000001016c0803
    x4: 0x0000000000000070   x5: 0x0000000000000073   x6: 0x000000016ef23580   x7: 0x00000000000006f0
    x8: 0x000000016ef23808   x9: 0x000000016ef237e8  x10: 0x00000001016e24a0  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x000000000000002a  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000101694624  x17: 0x0000000101695624  x18: 0x0000000000000000  x19: 0x000000016ef23828
   x20: 0x0000000100edc000  x21: 0x000000016ef237d8  x22: 0x0000000100edc000  x23: 0x000000016ef23988
   x24: 0x000000016ef23a58  x25: 0x000000016ef238c0  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x000000016ef23960   fp: 0x000000016ef237c0   lr: 0xe8408001016945ec
    sp: 0x000000016ef23740   pc: 0x0000000101696a1c cpsr: 0x80000000
   far: 0x0000000100edc000  esr: 0x92000007

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 3037
    thread_create: 0
    thread_set_state: 0

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by niyaton** [comment]
In my case, this problem was resolved after installed (updated) Xcode command-line tools.

**Comment by xhochy** [comment]
Otherwise, please have a look at the kernel logs as reported by `sudo log stream --predicate 'sender = "kernel"'` while running the Python processes. This should indicate which binaries are violating the code signature.

**Comment by lemontheme** [comment]
Updating Xcode CL tools (that's `xcode-select --install`, right?) didn't fix it for me. Instead – mostly from a place of impatience – I ended up nuking ~/miniforge3 and reinstalling everything. That did it for me.

@xhochy, I ran your command but forgot to save the output. I'm able to fish this out of my search history, though, in case it's of any help: 

```
CODE SIGNING: process 8951[python3.9]: rejecting invalid page [..]
```

**Comment by xhochy** [comment]
@lemontheme Thanks for the heads-up on this. If you encounter this again, `cp <filename> /tmp/temporary_file && ldid -S /tmp/temporary_file && mv /tmp/temporary_file <filename>` on the reported file should fix this. Though this should not happen by default. Thus if you encounter it, fix it with that command (the combination of cp/mv is important) but also open an issue on the respective feedstock of the package.

I'm closing this as we didn't get any information on the issue of the initial reporter @daiyoba but it seems to be solved for all others in some way.
