### ISSUE TITLE
Crashes using `mamba` on macOS Sonoma

### ISSUE THREAD

**Issue by pauldmccarthy** [conda-forge/miniforge#512]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Howdy,

(Reporting here for posterity - I think the main issue is https://github.com/curl/curl/issues/11893).

I have a couple of users reporting crashes when running `mamba env update` on macOS Sonoma. I don't have access to a Sonoma machine, so can only provide a few more details (if necessary), but I think the most relevant message that is emitted is:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringByStandardizingPath]: unrecognized selector sent to instance 0x600003af0050'
```

Searching around the internet, I stumbled across a [recently fixed issue in `curl`](https://github.com/curl/curl/issues/11893). 

So I suspect that this issue will be resolved with a new miniforge/mambaforge release that bundles the latest curl 8.4.0. 

Judging by #511, it sounds like this is already on the cards, so hopefully this be resolved without any further effort.

Thanks!

### Installed packages

```shell
Environment installed via [`Mambaforge-23.3.1-1-MacOSX-arm64.sh`](https://github.com/conda-forge/miniforge/releases/download/23.3.1-1/Mambaforge-23.3.1-1-MacOSX-arm64.sh)
```

### Environment info

```shell
Environment installed via [`Mambaforge-23.3.1-1-MacOSX-arm64.sh`](https://github.com/conda-forge/miniforge/releases/download/23.3.1-1/Mambaforge-23.3.1-1-MacOSX-arm64.sh)
```

**Comment by sorenwacker** [comment]
Same problem.

**Comment by fxcoudert** [comment]
This crash is typically because some library loaded (here, probably `curl`) should link to `CoreServices` but doesn't. This was fixed in Curl in this commit: https://github.com/curl/curl/commit/6ab7e1990bd548059f08c471d20537bca13c67b6

So this should be fixed by moving to curl >= 8.4.0

**Comment by jaimergp** [comment]
Does it work with `conda` too? With the new solver, it should be more or less the same result, but the download happens via a Python code path, so maybe it's not affected.

This should be the same (`--solver libmamba` not needed, just added for clarity):

```
$ conda create -n tmp python=3.10 --yes --solver=libmamba
```

**Comment by pauldmccarthy** [comment]
I'm afraid I don't have access to a Sonoma machine, so cannot be of much use. However I am still getting reports of this occurring with the latest Mambaforge (23.11.0). Confusingly I am also getting reports of successful installations on Sonoma, so there is another factor at play somewhere.

We have solved this issue in our system by switching to the latest [Miniconda release](https://docs.anaconda.com/free/miniconda/) (also versioned 23.11.0), and calling `conda` rather than `mamba` (which as @jaimergp points out is likely to be using `libmamba` under the hood).

For what it's worth, [here is a log file](https://github.com/conda-forge/miniforge/files/14309902/fsl_installation_20240210200955.log) of our installer script which uses mambaforge to set up a conda environment containing [our software](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/), in which the error has occurred. The installer does the following:
1. Downloads and installs [Mambaforge-23.11.0-0-MacOSX-arm64.sh](https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh)
2. Downloads our [environment specification](https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fsl-6.0.7.7_macos-M1.yml)
3. Runs `mamba env update -f <env>.yml` (We're aware that installing directly into the base environment is discouraged, but it has worked well for us in practice so far).

Note that our installer script is written in Python, and so a separate Python interpreter is required to run our script and to bootstrap the installation. One common theme amongst all of the reports I have received are that the Python interpreter used for running the installer script is an _Anaconda_ installation (e.g. `/Users/<username>/anaconda3/bin/python`). 

I had a wild theory that perhaps the Anaconda installation has an out-dated libcurl library, and that this library is somehow magically being loaded by the mambaforge Python interpreter, instead of the one installed into the mambaforge base environment. I asked a colleague of mine (with a M1 mac running Sonoma) to test this theory (install an old version of Anaconda with a broken libcurl, then use it to run our installer), but he wasn't able to reproduce the error. 

So I'm kind of stumped. But as I mentioned, this is not a problem for us, as with the switch to miniconda our users are no longer experiencing the error.

**Comment by k3rnel-pan1c-a** [comment]
any updates on this issue?

**Comment by Serge3leo** [comment]
Workaround: install curl from conda-forge.

For example, for me (macOS Sonoma 14.7.1, Python 3.12, Anaconda 2024.10):
```
$ conda list curl
...
curl                      8.12.1               h3a17b82_0  
...
$ conda search curl=8.12.1
# Name                       Version           Build  Channel             
curl                          8.12.1      h3a17b82_0  pkgs/main           
curl                          8.12.1      h5dec5d8_0  conda-forge         
$ conda install curl=8.12.1=h5dec5d8_0
```

Repair problem, `mamba` started fine. Seems fine.
