### ISSUE TITLE
__conda_reactivate not found after a fresh install and an update

### ISSUE THREAD

**Issue by ppoilbarbe** [conda-forge/miniforge#700]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

After a fresh install from https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh (corresponding, at this day to version 24.11.0-1), if I do "mamba update --yes --override-channels --channel conda-forge", there is an error "....etc/profile.d/mamba.sh: line 20: __conda_reactivate: command not found".
As said in tickets for mamba it was solved in version 2 of mamba.
But the downloaded script seems to install mamba 1.5.11.
Here is the output of the "mamba update" command:

```
$ bash Miniforge3-Linux-x86_64.sh -b -p $HOME/base-conda
PREFIX=/home/******/base-conda
Unpacking payload ...
Extracting _libgcc_mutex-0.1-conda_forge.tar.bz2
Extracting ca-certificates-2024.8.30-hbcca054_0.conda
.....
.....
.....
installation finished.
$ . $HOME/base-conda/etc/profile.d/conda.sh
$ . $HOME/base-conda/etc/profile.d/mamba.sh
$ mamba update --yes --override-channels --channel conda-forge --all --prefix $HOME/base-conda

Looking for: ['libsolv', 'zstandard', 'reproc', 'pip', 'pluggy', 'libcurl', 'ld_impl_linux-64', 'libev', 'lzo', 'ncurses', 'zstd', 'libarchive', 'krb5', 'pycparser', 'libffi', 'yaml-cpp', 'libmamba', 'libgcc', 'truststore', 'archspec', 'mamba', 'distro', 'fmt', 'hyperframe', 'libmambapy', 'pybind11-abi', 'libsqlite', 'hpack', 'tqdm', 'libuuid', 'python_abi', 'python', 'libnsl', 'pycosat', 'platformdirs', 'keyutils', 'tk', 'ruamel.yaml', 'bzip2', 'libexpat', 'h2', 'packaging', 'lz4-c', 'urllib3', 'conda-package-handling', 'menuinst', 'libgcc-ng', 'colorama', 'tzdata', 'libxml2', 'libstdcxx-ng', 'jsonpointer', 'boltons', 'frozendict', 'libstdcxx', '_openmp_mutex', 'ruamel.yaml.clib', 'liblzma', 'readline', 'openssl', 'requests', '_libgcc_mutex', 'cffi', 'ca-certificates', 'pysocks', 'conda', 'idna', 'libxcrypt', 'certifi', 'wheel', 'libzlib', 'libiconv', 'libnghttp2', 'brotli-python', 'charset-normalizer', 'libedit', 'c-ares', 'conda-package-streaming', 'libssh2', 'jsonpatch', 'libgomp', 'setuptools', 'reproc-cpp', 'conda-libmamba-solver']

conda-forge/noarch                                  17.9MB @  30.2MB/s  0.6s
conda-forge/linux-64                                40.8MB @  45.8MB/s  1.0s

Pinned packages:
  - python 3.12.*


Transaction

  Prefix: /home/******/base-conda

  Updating specs:

   - libsolv
   - zstandard
   - reproc
   - pip
   - pluggy
   - libcurl
   - ld_impl_linux-64
   - libev
   - lzo
   - ncurses
   - zstd
   - libarchive
   - krb5
   - pycparser
   - libffi
   - yaml-cpp
   - libmamba
   - libgcc
   - truststore
   - archspec
   - mamba
   - distro
   - fmt
   - hyperframe
   - libmambapy
   - pybind11-abi
   - libsqlite
   - hpack
   - tqdm
   - libuuid
   - python_abi
   - python
   - libnsl
   - pycosat
   - platformdirs
   - keyutils
   - tk
   - ruamel.yaml
   - bzip2
   - libexpat
   - h2
   - packaging
   - lz4-c
   - urllib3
   - conda-package-handling
   - menuinst
   - libgcc-ng
   - colorama
   - tzdata
   - libxml2
   - libstdcxx-ng
   - jsonpointer
   - boltons
   - frozendict
   - libstdcxx
   - _openmp_mutex
   - ruamel.yaml.clib
   - liblzma
   - readline
   - openssl
   - requests
   - _libgcc_mutex
   - cffi
   - ca-certificates
   - pysocks
   - conda
   - idna
   - libxcrypt
   - certifi
   - wheel
   - libzlib
   - libiconv
   - libnghttp2
   - brotli-python
   - charset-normalizer
   - libedit
   - c-ares
   - conda-package-streaming
   - libssh2
   - jsonpatch
   - libgomp
   - setuptools
   - reproc-cpp
   - conda-libmamba-solver
   - ca-certificates
   - certifi
   - openssl


  Package                     Version  Build            Channel           Size
────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────

  + cpp-expected                1.1.0  hf52228f_0       conda-forge       24kB
  + spdlog                     1.14.1  hed91bc2_1       conda-forge      196kB
  + nlohmann_json              3.11.3  he02047a_1       conda-forge      123kB
  + simdjson                   3.11.3  h84d6215_0       conda-forge      246kB

  Change:
────────────────────────────────────────────────────────────────────────────────

  - libarchive                  3.7.7  h4585015_2       conda-forge     Cached
  + libarchive                  3.7.7  h4585015_3       conda-forge      878kB
  - pip                        24.3.1  pyh8b19718_0     conda-forge     Cached
  + pip                        24.3.1  pyh8b19718_2     conda-forge        1MB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────

  - c-ares                     1.34.3  hb9d3cd8_1       conda-forge     Cached
  + c-ares                     1.34.4  hb9d3cd8_0       conda-forge      206kB
  - ca-certificates         2024.8.30  hbcca054_0       conda-forge     Cached
  + ca-certificates        2024.12.14  hbcca054_0       conda-forge      157kB
  - libcurl                    8.10.1  hbbe4b11_0       conda-forge     Cached
  + libcurl                    8.11.1  h332b0f4_0       conda-forge      423kB
  - libmamba                   1.5.11  hf72d635_0       conda-forge     Cached
  + libmamba                    2.0.5  hf72d635_0       conda-forge        2MB
  - libmambapy                 1.5.11  py312hf3f0a4e_0  conda-forge     Cached
  + libmambapy                  2.0.5  py312hf3f0a4e_0  conda-forge      624kB
  - conda                     24.11.0  py312h7900ff3_0  conda-forge     Cached
  + conda                     24.11.1  py312h7900ff3_0  conda-forge        1MB
  - certifi                 2024.8.30  pyhd8ed1ab_0     conda-forge     Cached
  + certifi                2024.12.14  pyhd8ed1ab_0     conda-forge      162kB
  - conda-libmamba-solver      24.9.0  pyhd8ed1ab_0     conda-forge     Cached
  + conda-libmamba-solver     24.11.1  pyhd8ed1ab_0     conda-forge       41kB
  - mamba                      1.5.11  py312h9460a1c_0  conda-forge     Cached
  + mamba                       2.0.5  hfdd0a45_0       conda-forge      477kB

  Summary:

  Install: 4 packages
  Change: 2 packages
  Upgrade: 9 packages

  Total download: 8MB

────────────────────────────────────────────────────────────────────────────────


cpp-expected                                        23.6kB @ 222.0kB/s  0.1s
ca-certificates                                    157.1kB @   1.1MB/s  0.1s
c-ares                                             206.1kB @   1.4MB/s  0.1s
libcurl                                            423.0kB @   2.3MB/s  0.2s
spdlog                                             195.7kB @   1.0MB/s  0.1s
libarchive                                         878.0kB @   4.6MB/s  0.2s
certifi                                            161.6kB @ 679.7kB/s  0.1s
libmamba                                             2.0MB @   8.0MB/s  0.1s
mamba                                              476.7kB @   1.9MB/s  0.1s
simdjson                                           246.5kB @ 745.2kB/s  0.1s
conda-libmamba-solver                               41.0kB @ 123.4kB/s  0.1s
libmambapy                                         623.7kB @   1.9MB/s  0.1s
conda                                                1.2MB @   3.4MB/s  0.1s
pip                                                  1.2MB @   3.6MB/s  0.1s
nlohmann_json                                      122.7kB @ 310.7kB/s  0.1s

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
__conda_reactivate : commande introuvable

$ mamba create --name test-env selenium
warning  libmamba You have not set the root prefix environment variable.
    To permanently modify the root prefix location, either:
      - set the 'MAMBA_ROOT_PREFIX' environment variable
      - use the '-r,--root-prefix' CLI option
      - use 'mamba shell init ...' to initialize your shell
        (then restart or source the contents of the shell init script)
    Continuing with default value: "/home/******/base-conda"
...
...
$ . $HOME/base-conda/etc/profile.d/conda.sh
$ . $HOME/base-conda/etc/profile.d/mamba.sh
$ mamba create --name test-env2 selenium
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache


Transaction

  Prefix: /home/******/base-conda/envs/test-env2
```
If I reread configuration files betwwen operations the problem disapeared.
As I did an install from a script which exit at the first non zero exit code (it was 127) I did not see everything.
So I edited my original issue.
Maybe it will disapear when mamba 2 will be directly integrated in Miniforge3.
I have a workarround for my script which now gets the output of the mamba. If output contains "__conda_reactivate" and exit code is 127 it continues.

### Installed packages

```shell
$ base-conda/bin/conda list
# packages in environment at /home/******/conda-base:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_1    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.4               hb9d3cd8_0    conda-forge
ca-certificates           2024.12.14           hbcca054_0    conda-forge
certifi                   2024.12.14         pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
conda                     24.11.1         py312h7900ff3_0    conda-forge
conda-libmamba-solver     24.11.1            pyhd8ed1ab_0    conda-forge
conda-package-handling    2.4.0              pyha770c72_1    conda-forge
conda-package-streaming   0.11.0             pyhd8ed1ab_0    conda-forge
cpp-expected              1.1.0                hf52228f_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
frozendict                2.4.6           py312h66e93f0_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_1    conda-forge
hpack                     4.0.0              pyhd8ed1ab_1    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_1    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_1    conda-forge
jsonpointer               3.0.0           py312h7900ff3_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libarchive                3.7.7                h4585015_3    conda-forge
libcurl                   8.11.1               h332b0f4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblzma                   5.6.3                hb9d3cd8_1    conda-forge
libmamba                  2.0.5                hf72d635_0    conda-forge
libmambapy                2.0.5           py312hf3f0a4e_0    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsolv                   0.7.30               h3509ff9_0    conda-forge
libsqlite                 3.47.2               hee588c1_0    conda-forge
libssh2                   1.11.1               hf672d98_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.5               h0d44e9d_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.10.0               h5888daf_1    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     2.0.5                hfdd0a45_0    conda-forge
menuinst                  2.2.0           py312h7900ff3_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nlohmann_json             3.11.3               he02047a_1    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pip                       24.3.1             pyh8b19718_2    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_1    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py312h66e93f0_2    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
python                    3.12.8          h9e4cc4f_1_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.5.post0         hb9d3cd8_0    conda-forge
reproc-cpp                14.2.5.post0         h5888daf_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.18.6          py312h66e93f0_1    conda-forge
ruamel.yaml.clib          0.2.8           py312h66e93f0_1    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
simdjson                  3.11.3               h84d6215_0    conda-forge
spdlog                    1.14.1               hed91bc2_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_0    conda-forge
truststore                0.10.0             pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
$ base-conda/bin/conda info

     active environment : None
       user config file : /home/******/.condarc
 populated config files : /home/******/base-conda/.condarc
                          /home/******/.condarc
          conda version : 24.11.1
    conda-build version : not installed
         python version : 3.12.8.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.11.1=0
                          __glibc=2.35=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /home/******/base-conda  (writable)
      conda av data dir : /home/******/base-conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/******/base-conda/pkgs
                          /home/******/.conda/pkgs
       envs directories : /home/******/base-conda/envs
                          /home/******/.conda/envs
               platform : linux-64
             user-agent : conda/24.11.1 requests/2.32.3 CPython/3.12.8 Linux/6.8.0-49-generic ubuntu/22.04.5 glibc/2.35 solver/libmamba conda-libmamba-solver/24.11.1 libmambapy/2.0.5
                UID:GID : 1822402247:1822400513
             netrc file : /home/******/.netrc
           offline mode : False
```

**Comment by jjerphan** [comment]
This has been introduced by https://github.com/conda/conda/pull/14277.

**Comment by hmaarrfk** [comment]
I'm really tempted to backport https://github.com/mamba-org/mamba/pull/3643

2.0.5 was just released with other challenges https://github.com/conda-forge/miniforge/issues/697 that you are helping fix (thanks!!!!)

but truthfully, it is always good to have a "range" of versions that are installable and usable so one can diagnose problems.

e.g. without the ability to downgrade within a range, tools like "git bisect" get REALLY difficult to use since you not only do you need to change your source, but your environment specs.

**Comment by jjerphan** [comment]
Isn't the cost of reverting https://github.com/conda/conda/pull/14277/ smaller?

**Comment by hmaarrfk** [comment]
This is for you to decide, but you now have the power to press merge 
https://github.com/mamba-org/mamba/pull/3702

**Comment by jjerphan** [comment]
Let's continue the discussion on https://github.com/mamba-org/mamba/pull/3702.

For now, a workaround is to downgrade to `conda<24.11`:

```
conda install -y -c conda-forge "conda<24.11"
```

**Comment by ppoilbarbe** [comment]
> I've been seeing this too, though i'm not sure where best to report this upstream.
> 
> cc: @conda-forge/conda @conda-forge/mamba

I was not sure too. But as I install miniforge which integrates both, I thought that it may be a good place.

**Comment by hmaarrfk** [comment]
jjerpan responded ;) and is working to address the issue ;)

**Comment by jjerphan** [comment]
This is being fixed by conda.

See: https://github.com/conda/conda/pull/14277#issuecomment-2554856593

**Comment by jjerphan** [comment]
[conda 24.11.2 has been released hours ago](https://github.com/conda/conda/releases/tag/24.11.2); can you let us know if updating conda solves the issue?

**Comment by hmaarrfk** [comment]
Users will need to wait until https://github.com/conda-forge/conda-feedstock is released for conda-forge.

**Comment by jjerphan** [comment]
Should be solved once https://github.com/conda-forge/conda-feedstock/pull/248 is merged and its builds are published.

**Comment by hmaarrfk** [comment]
Thanks! It seems merged. I'll close this and work toward a new release.

I'm curious if we can go to mamba 2.0.5. I'll try to recreate the other blocker we have.

**Comment by nwalters512** [comment]
Is this expected to be fixed yet? I'm still seeing the error described here when using `mamba install ...` after downloading the latest release from `https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-${arch}.sh`. Do I need to wait for the version with mamba 2.0.5 to be released?

**Comment by jjerphan** [comment]
Can you share the version of mamba and conda which you have installed, @nwalters512?

**Comment by nwalters512** [comment]
Sure thing:

```
(base) bash-5.2# mamba --version
mamba 1.5.11
conda 24.11.0
```

For what it's worth, I also upgraded to conda 24.11.2 and I'm still experiencing the issue.

Here's a full reproduction; I was running this in a `amazonlinux:2023` Docker image (`docker run --rm -it amazonlinux:2023 /bin/bash`).

```sh
export arch=`uname -m`
curl -sfLO "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-${arch}.sh"
chmod +x Miniforge3-Linux-aarch64.sh
./Miniforge3-Linux-aarch64.sh -b
/root/miniforge3/bin/mamba init bash
source /root/.bashrc

mamba --version         
# mamba 1.5.11
# conda 24.11.0

# at the very end, this fails with "bash: __conda_reactivate: command not found"
mamba install pygraphviz

# try upgrading conda
conda update conda

# verify new version
mamba --version
# mamba 1.5.11
# conda 24.11.2

# this fails the same way as above
mamba install pygraphviz
```

**Comment by jjerphan** [comment]
Can you update to mamba 1.5.12?

**Comment by nwalters512** [comment]
That did not resolve the error.

**Comment by hmaarrfk** [comment]
I'm releasing https://github.com/conda-forge/miniforge/releases/tag/24.11.2-0 just now, it will be live in a few hours. Lets close if that can be resolved with that one.

There were some growing pains with mamba2 sorry :(

**Comment by nwalters512** [comment]
Thanks for releasing that new version! After the upgrade, `mamba install pygraphviz==1.14` behaves very strangely. It hangs after the following output:

```
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ 
- 
done
```

After several minutes, it starts printing the following roughly once per second (this is verbatim, I did not accidentally remove any part of the line):

```
is deprecated and will be removed in 25.9. Use instead.
```

I let this run for a few minutes before killing the process; it showed no signs of stopping or doing anything different.

Because of this, I'm unfortunately unable to say whether this resolves the initial issue here 😢 This is almost definitely completely unrelated to the problem described by this issue. I'd appreciate any guidance you could offer about where I could file a separate issue about this new problem.

**Comment by hmaarrfk** [comment]
I've unfortunately been hitting this too...

**Comment by hmaarrfk** [comment]
Ok i've pulled the latest release again. not a good start to the year....

**Comment by jjerphan** [comment]
The repeated message comes from https://github.com/conda/conda/pull/14455.

**Comment by KRRT7** [comment]
I just hit this as well.

install on macOS 15.2
```
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh
```

```
mamba --version
mamba 1.5.11
conda 24.11.0
```

after installing a package with mamba i.e `mamba install poetry` at the very end I get this
`mamba:8: command not found: __conda_reactivate`

**Comment by jjerphan** [comment]
This will be fixed once https://github.com/conda-forge/conda-feedstock/pull/251 is merged and the associated version of conda and mamba 1.5.12 are used.

**Comment by hmaarrfk** [comment]
Please try: https://github.com/conda-forge/miniforge/releases/tag/24.11.2-1

**Comment by hmaarrfk** [comment]
let me know if the issue persists

**Comment by KRRT7** [comment]
> Please try: https://github.com/conda-forge/miniforge/releases/tag/24.11.2-1

I'm still pretty unfamiliar with mamba, do I just `mamba upgrade conda`?

**Comment by hmaarrfk** [comment]
please just open a new issue for help.

there are stock questions we ask everybody to better help

**Comment by nwalters512** [comment]
I can confirm that things are working again with the `latest` download from GitHub! Thanks for your work to get this fixed 🙏
